language: php

php:
  - 7.2

addons:
  ssh_known_hosts: back1.igotta.beer

cache:
  directories:
    - $HOME/.composer/cache
    - web/node_modules

before_install:
    - composer self-update
    - composer validate --no-check-publish

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - cd web/
  - npm install

script:
  - npm run build

before_deploy:
  - cd .. && pwd
  - openssl aes-256-cbc -K $encrypted_5b0d89742976_key -iv $encrypted_5b0d89742976_iv -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash deploy/travis_deploy.sh $TRAVIS_BUILD_DIR
  on:
    branch: master
